name: Publishing GitHub Packages

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  check-java-25:
    name: Checking on JDK 25
    uses: ./.github/workflows/ci.yml

  test-legacy-jdk:
    name: Testing on Legacy JDKs
    uses: ./.github/workflows/testing-legacy-jdk.yml

  publish:
    name: Publish to GitHub Packages
    needs:
      - check-java-25
      - test-legacy-jdk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v5

      - name: Publish to GitHub Packages
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload publish artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: publish-artifacts
          path: |
            build/test-results/**
            build/reports/**
            build/publications/**
